---
- name: Play for installing nginx on webservers
  hosts: all
  gather_facts: yes
  become: yes 
  #or we can give > become_user: root
  tasks:
  - name: Perform apt update & install basic packages
    shell: apt update && apt install -y unzip jq net-tools
    when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "20.04" )
  
  - name: Install Nginx webserver Application
    #shell: apt install -y nginx 
    #We can use this "shell Module" or "package" module as follows
    #package: 
    #  name: nginx  or
    #  name:
        # - nginx
    #  state: present
    #We can also use "apt" Module as follows for ubuntu system
    apt:
     name: nginx
     #state: present or 
     state: latest
  
  - name: Start nginx service
    #shell: service nginx start
    #We can use this "shell Module" or "service" module as follows
    service: 
     name: nginx
     state: started
...